## NumPy
![Python logo](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkiN-2R8BNLYDu7gn69yC7V-6p441dAJG2MQ&s)

### What is a Python NumPy?
NumPy is a Python package which stands for ‘Numerical Python’. It is the core library for 
scientific computing, which contains a powerful n-dimensional array objects, provide tools for 
integrating C, C++ etc. It is also useful in linear algebra, random number capability etc. NumPy array 
can also be used as an efficient multi-dimensional container for generic data. 
### NumPy Array:
Numpy array is a powerful N-dimensional array object which is in the form of rows 
and columns. We can initialize numpy arrays from nested Python lists and access it elements. Numpy 
arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices 
are 2-d (but you should note a matrix can still have only one row or one column).
### How do I install NumPy?
To install Python NumPy, go to your command prompt and type “pip install numpy”. Once the 
installation is completed, go to your IDE and simply import it by typing: “import numpy as np”
- Here, I have different elements that are stored in their respective memory locations. It is said to be two dimensional because it has rows as well as columns. In the above image, we have 3 columns and 4 rows available.

In [1]:
!pip install numpy

#### How to create NumPy arrays :
Syntax: numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
 

In [2]:
import numpy as np

In [3]:
# Single-dimensional Numpy Array:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# Multi-dimensional Array:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


### NumPy Operations

#### ndim:
To find the dimension of the array, whether it is a two-dimensional array or a single 
dimensional array use ndim function..

In [5]:
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


#### itemsize:
To calculate the byte size of each element in array use itemsize(). In the below code, I have 
defined a single dimensional array and with the help of ‘itemsize’ function, we can find the size 
of each element

In [6]:
a = np.array([(1,2,3)])
print(a.itemsize)

4


So every element occupies 4 byte in the above numpy array

#### dtype:
 if you want to know the data type of a particular element, you can use ‘dtype’ function which will print the datatype along with the size.

In [7]:
a = np.array([(1,2,3)])
print(a.dtype)

int32


As you can see, the data type of the array is integer 32 bits. Similarly, you can find the size and shape of 
the array using ‘size’ and ‘shape’ function respectively.

#### size: 
 returns the no. of elements present in an array
#### shape: 
 it represents the shape of array i.e no. of rows and no. of columns 

In [8]:
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [9]:
a = np.array([(1,2,3),(4,5,6)])
print(a.size)
print(a.shape)

6
(2, 3)


### reshape:
- Reshape is when you change the number of rows and columns which gives a new view to an object. we have 3 columns and 2 rows which has converted into 2 columns and 3 rows.

In [10]:
a = np.array([(8,9,10),(11,12,13)])
print("original array is\n",a)
a=a.reshape(3,2)
print("after converting\n",a)

original array is
 [[ 8  9 10]
 [11 12 13]]
after converting
 [[ 8  9]
 [10 11]
 [12 13]]


### Slicing:
Slicing is basically extracting particular set of elements from an array. This slicing operation 
is pretty much similar to the one which is there in the list as well. Consider the following 


```python
Syntax for 1d-array:
Array_name[start:end:step]
Synatax for 2d-array:
Array_name[start:end:step, start:end: step]
```

In [11]:
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a)
print(a[0:,0::2])

[[1 2 3 4]
 [3 4 5 6]]
[[1 3]
 [3 5]]


- min(): returns the minimum element from array 
- max():returns the maximum element from array
- sum():returns the sum off all elements present in an array

In [12]:
a= np.array([1,2,3])
print(a.min()) 
print(a.max()) 
print(a.sum())

1
3
6


above min,max,sum functions works only for one dimensional array.

- For two dimensional array use axis object 
i.e for columns sum use arrayname.sum(axis=0)
- for rows sum use arrayname.sum(axis=1)


In [13]:
a= np.array([(1,4,3),(0,2,5)])
print(a)
print(a.sum(axis=0)) 
print(a.sum(axis=1)) 
print(a.min(axis=0)) 
print(a.min(axis=1)) 
print(a.max(axis=0))
print(a.max(axis=1))

[[1 4 3]
 [0 2 5]]
[1 6 8]
[8 7]
[0 2 3]
[1 0]
[1 4 5]
[4 5]


### Square Root & Standard Deviation:

#### sqrt():
it returns array with Square Root of all element present in an array
```python
syntax:numpy.sqrt(array_name)
```
#### std():
:is a measure of the amount of variation or dispersion of a set of values.
In python using std() function we can find the Standard Deviation of the given array values
```python
Syntax: numpy.std(array_name)
```

In [14]:
a=np.array([(1,2,9),(16,4,1,)])
print(np.sqrt(a))
print("Standard Deviation is:",np.std(a))

[[1.         1.41421356 3.        ]
 [4.         2.         1.        ]]
Standard Deviation is: 5.439056290693573


#### Note:
we can also perform addition ,subtraction, multiplication and division operations on arrays

#### for addition/substraction/division/multiplication

In [15]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print("substraction of two arrays is:\n",x-y)
print("addtion of two arrays is:\n",x*y)
print("division of two arrays is :\n",x/y)
print("multiplication of two arrays is:\n",x*y)

substraction of two arrays is:
 [[0 0 0]
 [0 0 0]]
addtion of two arrays is:
 [[ 1  4  9]
 [ 9 16 25]]
division of two arrays is :
 [[1. 1. 1.]
 [1. 1. 1.]]
multiplication of two arrays is:
 [[ 1  4  9]
 [ 9 16 25]]


#### Note:
(*) is used for array multiplication (multiplication of corresponding elements of two arrays) not 
matrix multiplication. To multiply two matrices, we use dot() method


In [16]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2),(3,4),(5,6)])
print(x.dot(y))

[[22 28]
 [40 52]]


### Vertical & Horizontal Stacking
if you want to concatenate two arrays and not just add them, you can perform it using two 
ways – vertical stacking and horizontal stacking.

In [17]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(7,8,9),(4,5,6)])
print("vertical stacking of two matrices is:\n",np.vstack((x,y)))
print("horizontal stacking of two matrices is:\n",np.hstack((x,y)))

vertical stacking of two matrices is:
 [[1 2 3]
 [3 4 5]
 [7 8 9]
 [4 5 6]]
horizontal stacking of two matrices is:
 [[1 2 3 7 8 9]
 [3 4 5 4 5 6]]


### ravel():
to convert one numpy array into a single column values

In [18]:
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


### Built-in Methods

#### arange():
Return evenly spaced values within a given interval.
```python
Syntax: arrange(start,stop,step, dtype=None)
```

In [19]:
np.arange(3)

array([0, 1, 2])

In [20]:
np.arange(4.0)

array([0., 1., 2., 3.])

In [21]:
np.arange(3,7)

array([3, 4, 5, 6])

In [22]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [23]:
np.arange(3,10,2,dtype="complex")

array([3.+0.j, 5.+0.j, 7.+0.j, 9.+0.j])

#### zeros():
Return a new array of given shape and type, filled with zeros
```python
Syntax: zeros(shape, dtype=float, order='C')
```

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [26]:
np.zeros((2, 1))

array([[0.],
       [0.]])

In [27]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [28]:
print(np.zeros((2, 1)))

[[0.]
 [0.]]


#### Ones():
Return a new array of given shape and type, filled with ones, and default datatype is float
```python
Syntax:ones(shape, dtype=None, order='C')
```

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [31]:
np.ones((2, 1))

array([[1.],
       [1.]])

In [32]:
s = (2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])

#### Linspace():
Return evenly spaced numbers over a specified interval.
```python
Syntax:linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```

In [33]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [34]:
 np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [35]:
 np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [36]:
np.linspace(1,100,num=4,dtype=int)

array([  1,  34,  67, 100])

### random():
it returns Random Number Generation array
 Utility functions of random function

#### rand():
creates array of specifid shape and fills it with random values as per uniform distribution

In [37]:
print(np.random.rand(2,2))

[[0.35481073 0.55122336]
 [0.49048979 0.69590133]]


#### randn():
creates array of specifid shape and fills it with random values as per standard normal distribution

In [38]:
print(np.random.randn(2,2))

[[-1.30581103 -0.05174023]
 [-0.77054159 -0.63347237]]


#### randint():
crates array of specified shape and fills it with random integers from low(inclusive) to 
high(exclusive). If high is not mentioned then the interval will be [0,low]

```python
Syntax: randint(low, high=None, size=None, dtype='l')
```

In [39]:
print(np.random.randint(1, size=5))

[0 0 0 0 0]


In [40]:
print(np.random.randint(3, size=5))

[1 2 0 0 1]


In [41]:
print(np.random.randint(1,5, size=(2, 4)))

[[4 1 4 3]
 [1 1 3 2]]


In [42]:
print(np.random.randint(4,5, size=(2, 3)))

[[4 4 4]
 [4 4 4]]


#### eye():
Creates an identity matrix

In [43]:
print(np.eye(2,2))

[[1. 0.]
 [0. 1.]]


In [44]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
print(np.eye(2,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


####  concatenate():
Join a sequence of arrays along an existing axis.
```python
Synatx: concatenate((a1, a2, ...), axis=0, out=None)
```
a1, a2, ... : sequence of arrays: The arrays must have the same shape, except in the dimension
 corresponding to 'axis'.

In [46]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

#### Matrix creation using matrix class
A matrix is a two-dimensional data structure where numbers are arranged into rows and 
columns.
```python
Syntax: numpy.matrix(data, dtype=None, copy=True)
```
- Returns a matrix from an array-like object, or from a string of data

In [48]:
a = np.matrix('1 2; 3 4')
print(a)

[[1 2]
 [3 4]]


In [49]:
a = np.matrix([[1, 2], [3, 4]])
print(a)


[[1 2]
 [3 4]]


#### Matrix addition(+),substraction(-), multiplication(*)

In [50]:
x= np.matrix([(1,2,3),(3,4,5),(4,5,6)])
y= np.matrix([(1,2,3),(3,4,6),(5,6,7)])

In [51]:
print("addition of two matrices is:\n",x+y)

addition of two matrices is:
 [[ 2  4  6]
 [ 6  8 11]
 [ 9 11 13]]


In [52]:
print("substraction of two matrices is:\n",x-y)

substraction of two matrices is:
 [[ 0  0  0]
 [ 0  0 -1]
 [-1 -1 -1]]


In [53]:
print("multiplication of two matrices is:\n",x*y)

multiplication of two matrices is:
 [[22 28 36]
 [40 52 68]
 [49 64 84]]


#### Matrix transpose():
The transpose of a matrix is obtained by moving the rows data to the column and columns data 
to the rows. If we have an array of shape (X, Y) then the transpose of the array will have the shape (Y, 
X)

In [54]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:\n",a)
a_t = a.transpose()
print("Transposed Array:\n",a_t)

Original Array:
 [[1 2 3]
 [4 5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [55]:
a = np.matrix([[1, 2, 3], [4, 5, 6]])
print("Original matrix:\n",a)
print("Transposed matrix:\n",a.T)

Original matrix:
 [[1 2 3]
 [4 5 6]]
Transposed matrix:
 [[1 4]
 [2 5]
 [3 6]]


#### Inverse of a matrix:
We use numpy. linalg. inv() function to calculate the inverse of a matrix. The inverse of a matrix is such 
that if it is multiplied by the original matrix, it results in identity matrix


In [56]:
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result = np.linalg.inv(m)
print("Inverse of a given matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Inverse of a given matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


## Some additional operations 

In [57]:
from time import process_time

In [58]:
list1=[i for i in range(10000000)]
start_time=process_time()
list1=[i+10 for i in list1] #adding five to each number
end_time=process_time()
print(end_time-start_time)

1.953125


In [59]:
array1=np.array([i for i in range(10000000)])
start_time=process_time()
array1+=10
end_time=process_time()
print(end_time-start_time)

0.015625


In [60]:
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [61]:
Array1=np.array([1,2,3,4,5])
print(Array1)
print(type(Array1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [62]:
x=np.arange(1,10,2) # from 1 to 10 with step size 2
print(x)

[1 3 5 7 9]


In [63]:
x=np.random.rand(5)
print(x)

[0.22743127 0.15955624 0.28529162 0.29154501 0.55735255]


In [64]:
list1=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix=np.array(list1)
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
# 2*3 matrix contain from zero to one
x=np.random.rand(2,3)
print(x)

[[0.41504954 0.1499676  0.23502305]
 [0.74382146 0.54170172 0.88294935]]


In [66]:
# random values follows std normal distribution means whose mean is zero and std dev is 1
x=np.random.randn(5)
print(x)

[-0.43220117  1.43000712  1.36736339  0.55426689 -0.30273077]


In [67]:
# random values follows std normal distribution means whose mean is zero and std dev is 1
x=np.random.randn(3,4)
print(x)

[[-0.95232934 -0.19883488  0.37950924 -0.24962288]
 [ 1.17777945 -0.37651001  1.98694541  0.67379512]
 [ 1.20186166 -0.93266277 -0.64100335 -0.44505077]]


In [68]:
x=np.random.randint(10,100,(3,4))
print(x)

[[36 80 86 70]
 [57 79 70 46]
 [10 70 30 39]]


In [69]:
# now create two dimentional array (with defining values at float values)
array2=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(array2)
array2.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

In [70]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [71]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [72]:
x=np.full((4,4),5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [73]:
# create array with random values
x=np.random.random((3,4))
print(x)

[[0.73935559 0.6602988  0.15297479 0.41823396]
 [0.91701025 0.741273   0.20199678 0.38055958]
 [0.21309894 0.64396206 0.44031578 0.33161941]]


In [74]:
# create random int values
x=np.random.randint(10,100,(3,4))
print(x)

[[74 89 94 69]
 [85 90 28 40]
 [77 63 84 42]]


In [75]:
# creating array of evenly spaced values
x=np.linspace(10,30,5)
print(x)

[10. 15. 20. 25. 30.]


In [76]:
# converting list to array
list1=[10,20,30,40,50]
array1=np.asarray(list1)
print(array1)
type(array1)

[10 20 30 40 50]


numpy.ndarray

In [77]:
x=np.random.randint(10,99,(4,5))
print(x)
print("Shape of the array:\n ",x.shape)

[[64 95 93 67 30]
 [67 65 37 80 85]
 [43 57 73 79 73]
 [60 58 47 96 73]]
Shape of the array:
  (4, 5)


In [78]:
# dimenation of the array
x.ndim

2

In [79]:
# number of the element present in the array
x.size

20

In [80]:
#checking the datatype of the element in the array
x.dtype

dtype('int32')

In [81]:
myarr=np.random.randint(10,20,10)
print(myarr)

[14 11 13 18 16 11 17 14 17 12]


In [82]:
myarr.max()

18

In [83]:
# index location of max value
myarr.argmax()

3

In [84]:
myarr.min()

11

In [85]:
#index location of min value
myarr.argmin()

1

In [86]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list1+list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [87]:
a=np.random.randint(10,20,(3,3))
b=np.random.randint(20,30,(3,3))
print(a)
print(b)

[[11 19 10]
 [14 11 16]
 [15 13 19]]
[[28 22 27]
 [20 27 26]
 [22 27 28]]


In [88]:
print(a+b)

[[39 41 37]
 [34 38 42]
 [37 40 47]]


In [89]:
print(a-b)

[[-17  -3 -17]
 [ -6 -16 -10]
 [ -7 -14  -9]]


In [90]:
print(a*b)

[[308 418 270]
 [280 297 416]
 [330 351 532]]


In [91]:
print(a/b) 

[[0.39285714 0.86363636 0.37037037]
 [0.7        0.40740741 0.61538462]
 [0.68181818 0.48148148 0.67857143]]


In [92]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [94]:
arr/arr

C:\Users\Saimo\AppData\Local\Temp\ipykernel_18876\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [97]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [98]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [99]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [100]:
np.log(arr)

C:\Users\Saimo\AppData\Local\Temp\ipykernel_18876\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr.min()

0

In [103]:
arr.max()

10

In [104]:
arr.mean()

5.0

In [105]:
arr.std()

3.1622776601683795

In [106]:
arr.var()

10.0

In [107]:
arr=np.random.randint(1,10,(5,5))
arr

array([[8, 6, 8, 1, 2],
       [7, 8, 9, 9, 5],
       [3, 6, 2, 1, 4],
       [1, 8, 4, 6, 6],
       [9, 3, 5, 2, 4]])

In [108]:
arr.sum(axis=0) 

array([28, 31, 28, 19, 21])

In [109]:
arr.sum(axis=1)

array([25, 38, 16, 25, 23])

In [110]:
array1=np.random.randint(10,20,(2,3))
print(array1)
array1.shape

[[18 18 11]
 [10 18 11]]


(2, 3)

In [111]:
trans=np.transpose(array1)
print(trans)
trans.shape

[[18 10]
 [18 18]
 [11 11]]


(3, 2)

In [112]:
a=np.random.randint(10,30,(2,3))
print(a)
print(a.shape)

[[22 10 29]
 [29 28 29]]
(2, 3)


In [113]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[22 10]
 [29 29]
 [28 29]]
(3, 2)


### Numpy Indexing and selection
- Grabbing single element
- Grabbing a slice of element
- Brodcasting selection
- Indexing and selection in two dimentions
- Condition Selection


In [114]:
myarr=np.arange(0,11)
print(myarr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [115]:
myarr[3]

3

In [116]:
myarr[3:5] 

array([3, 4])

In [117]:
myarr[:5]

array([0, 1, 2, 3, 4])

In [118]:
myarr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [119]:
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
myarr[0:5]=100

In [121]:
myarr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [122]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
slice_of_array=arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [124]:
slice_of_array[:]=99
slice_of_array

array([99, 99, 99, 99, 99])

In [125]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [126]:
arr_copy=arr.copy()

In [127]:
arr_copy[:]=100

In [128]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [129]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [130]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [131]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [132]:
arr_2d=np.random.randint(10,99,(3,3))
arr_2d

array([[21, 55, 24],
       [80, 24, 69],
       [91, 18, 82]])

In [133]:
arr_2d.shape

(3, 3)

In [134]:
arr_2d[0]

array([21, 55, 24])

In [135]:
# to grab third element in the first row which is 41
arr_2d[0][2]

24

In [136]:
# to get some slice or subsection of matrix
arr_2d

array([[21, 55, 24],
       [80, 24, 69],
       [91, 18, 82]])

In [137]:
arr_2d[:2,1:]

array([[55, 24],
       [24, 69]])

In [138]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [139]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [140]:
arr=np.arange(0,11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [142]:
bool_arr=arr>4

In [143]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [144]:
# same result can be obtained by following code
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [148]:
print("-----"*3+" "+"THE END"+" " + "-----"*3)

--------------- THE END ---------------


Author: [Moguloju_Sai](https://linktr.ee/Moguloju_Sai)